CATALOGUE_HOST: catalogue.backend-{{ env }}.lakshmi.cyou
USER_HOST: user.lakshmi.backend-{{ env }}.cyou
CART_HOST: cart.lakshmi.backend-{{ env }}.cyou
SHIPPING_HOST: shipping.backend-{{ env }}.lakshmi.cyou
PAYMENT_HOST: payment.backend-{{ env }}.lakshmi.cyou
